import type { ComponentType } from "react";
import {
  Home,
  Map,
  BookOpen,
  Code2,
  User,
  Trophy,
  Zap,
  Flame,
  Heart,
  Check,
  CheckCircle2,
  PauseCircle,
  XCircle,
  CircleDot,
  Circle,
  Lock,
  Play,
  Pause,
  Search,
  Bell,
  Star,
  ArrowRight,
  ArrowLeft,
  ChevronRight,
  ChevronDown,
  Plus,
  X,
  RefreshCw,
  TerminalSquare,
  Eye,
  Target,
  Clock,
  Gift,
  Sparkles,
  List,
  Settings,
  Timer,
  type LucideProps,
} from "lucide-react";

type IconCmp = ComponentType<LucideProps>;

function filled(Cmp: IconCmp): IconCmp {
  const Wrapped: IconCmp = (props) => <Cmp fill="currentColor" {...props} />;
  Wrapped.displayName = `Filled(${Cmp.displayName ?? "Icon"})`;
  return Wrapped;
}

export const I = {
  home: Home,
  map: Map,
  book: BookOpen,
  code: Code2,
  user: User,
  trophy: Trophy,
  bolt: Zap,
  flame: Flame,
  heart: filled(Heart),
  heartO: Heart,
  check: Check,
  done: CheckCircle2,
  pause: PauseCircle,
  skip: XCircle,
  current: CircleDot,
  todo: Circle,
  lock: Lock,
  play: filled(Play),
  search: Search,
  bell: Bell,
  star: filled(Star),
  arrow: ArrowRight,
  arrowL: ArrowLeft,
  chevR: ChevronRight,
  chevD: ChevronDown,
  plus: Plus,
  close: X,
  refresh: RefreshCw,
  terminal: TerminalSquare,
  eye: Eye,
  target: Target,
  clock: Clock,
  gift: Gift,
  spark: Sparkles,
  list: List,
  settings: Settings,
  fire: filled(Flame),
  timer: Timer,
  pauseSimple: Pause,
} satisfies Record<string, IconCmp>;

export type IconKey = keyof typeof I;
